name: sendStGn

on:
  schedule:
    - cron: "55 17 * * *"    #runs at 17:55 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
            
      - name: Run Python script
        env:
          REQUESTURL: ${{ secrets.REQUESTURL }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python StGn.py
